-- Create inventory_items table (single source of truth for item list)
CREATE TABLE IF NOT EXISTS inventory_items (
  id          UUID    DEFAULT gen_random_uuid() PRIMARY KEY,
  section     TEXT    NOT NULL,
  name        TEXT    NOT NULL,
  unit        TEXT    NOT NULL,
  sort_order  INTEGER NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE inventory_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "authenticated_full_access" ON inventory_items
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Seed all items (sort_order gaps of 10 leave room to insert between items)
INSERT INTO inventory_items (section, name, unit, sort_order) VALUES
-- Kühlhaus
('Kühlhaus','Guacamole','1/6 GN groß',10),
('Kühlhaus','Schärfemix','Beutel (0.5kg)',20),
('Kühlhaus','Maissalsa','1/6 GN groß',30),
('Kühlhaus','Tomatensalsa','1/6 GN groß',40),
('Kühlhaus','Sour Cream','1/6 GN groß',50),
('Kühlhaus','Marinade Chicken','Beutel (1.0kg)',60),
('Kühlhaus','Pico de Gallo','1/2 GN',70),
('Kühlhaus','Crema Nogada','Beutel (1.0kg)',80),
('Kühlhaus','Käse Gouda','Beutel (5.0kg)',90),
('Kühlhaus','Gouda Scheiben Gringa','Packung',100),
('Kühlhaus','Ciabatta','Stück',110),
('Kühlhaus','Brownie','Blech',120),
('Kühlhaus','Carlota de Limon','Stück',130),
('Kühlhaus','Schoko- Avocado Mousse','Blech',140),
('Kühlhaus','Mole','1/6 GN groß',150),
('Kühlhaus','Marinade Al Pastor','Beutel (1.5kg)',160),
('Kühlhaus','Barbacoa','1/6 GN groß',170),
('Kühlhaus','Chili con Carne','1/6 GN groß',180),
('Kühlhaus','Cochinita','1/6 GN groß',190),
('Kühlhaus','Kartoffel Würfel','Beutel (3.0kg)',200),
('Kühlhaus','Vinaigrette','Behälter (1.0l)',210),
('Kühlhaus','Honig Sesam / Senf','Behälter (1.0l)',220),
('Kühlhaus','Pozole','Beutel (1.0kg)',230),
('Kühlhaus','Zwiebeln karamellisiert','Beutel (1.0kg)',240),
('Kühlhaus','Karotten karamellisiert','Beutel (10 Stück)',250),
('Kühlhaus','Bohnencreme','Beutel (2.5kg)',260),
('Kühlhaus','Alambre - Zwiebel','Beutel (2.0kg)',270),
('Kühlhaus','Weizen Tortillas 12cm','Kisten',280),
('Kühlhaus','Tortillas 30cm','Kisten',290),
('Kühlhaus','Frische Habaneros','Stück',300),
('Kühlhaus','Salsa Habanero','Beutel (1.5kg)',310),
('Kühlhaus','Salsa Verde','Beutel (2.0kg)',320),
('Kühlhaus','Chipotle SourCream','Beutel (2.0kg)',330),
('Kühlhaus','Salsa de Jamaica','Beutel (0.5kg)',340),
('Kühlhaus','Salsa Torta','Beutel (1.0kg)',350),
('Kühlhaus','Humo Salsa','Flasche',360),
('Kühlhaus','Fuego Salsa','Flasche',370),
('Kühlhaus','Oliven entkernt','Glas',380),
('Kühlhaus','Chiles Poblanos','Stück',390),
('Kühlhaus','Salsa Pitaya','Beutel (0.5kg)',400),
('Kühlhaus','Mais Tortillas 12cm','Beutel (50 Stk)',410),
('Kühlhaus','Blau Mais Tortillas 15cm','Beutel (40 Stk)',420),
('Kühlhaus','Queso Cotija','Pack (1.0kg)',430),
('Kühlhaus','Queso Oaxaca','Pack (1.0kg)',440),
('Kühlhaus','Queso Chihuahua','Pack (1.0kg)',450),
('Kühlhaus','Rinderfilet Steak','Beutel (250g)',460),
('Kühlhaus','Filetspitzen','Beutel (100g)',470),
('Kühlhaus','Hähnchenkeule (ganz)','Beutel (2 Stück)',480),
('Kühlhaus','Mole Rojo','Beutel (2.0kg)',490),
('Kühlhaus','Chorizo','Beutel (1.0kg)',500),
('Kühlhaus','Carne Vegetal','Beutel (1.0kg)',510),
('Kühlhaus','Costilla de Res','Beutel (4 Portionen)',520),
('Kühlhaus','Salsa für Costilla de Res','Beutel (2L)',530),
('Kühlhaus','Rote Zwiebeln eingelegt','1/6 GN groß',540),
('Kühlhaus','Pulpo (Chipulpotle)','Beutel (100 g)',550),
('Kühlhaus','Salsa Pulpo','Beutel (0.5kg)',560),
('Kühlhaus','Birria','Beutel (2.0kg)',570),
('Kühlhaus','Salsa Birria','Beutel (1.0kg)',580),
('Kühlhaus','Füllung Nogada','Beutel (1.0kg)',590),
('Kühlhaus','H-Milch 3,5%','Packung',600),
-- Tiefkühler
('Tiefkühler','Alambre - Paprika Streifen','Beutel (2.5kg)',610),
('Tiefkühler','Gambas','Beutel (1.0kg)',620),
('Tiefkühler','Weizentortillas 20cm','Karton',630),
-- Trockenware
('Trockenware','Reis','Beutel (1kg)',640),
('Trockenware','Schwarze Bohnen','Sack (5kg)',650),
('Trockenware','Salz','Eimer (10kg)',660),
('Trockenware','Zucker','Packung (1.0kg)',670),
('Trockenware','Brauner Zucker','Packung',680),
('Trockenware','Pfeffer','Packung',690),
('Trockenware','Pfeffer geschrotet','Packung',700),
('Trockenware','Rapsöl','Kanister (10L)',710),
('Trockenware','Tajin','Packung',720),
('Trockenware','Limettensaft (750ml Metro)','Flasche',730),
-- Regale
('Regale','Große Bowl togo Schale','Packungen (40 Stk)',740),
('Regale','Große Bowl togo Deckel','Packungen (40 Stk)',750),
('Regale','Kleine Bowl togo Schale','Packungen (40 Stk)',760),
('Regale','Kleine Bowl togo Deckel','Packungen (40 Stk)',770),
('Regale','Dressingsbecher Schale','50er Pack',780),
('Regale','Dressingsbecher Deckel','50er Pack',790),
('Regale','Alufolie','Rolle',800),
('Regale','Backpapier','Rolle',810),
('Regale','Trayliner Papier','Karton',820),
('Regale','Weiße Serviette','Karton',830),
('Regale','Zig-Zag Papier','Karton',840),
('Regale','Müllbeutel Blau 120L','120L Rolle',850),
('Regale','Handschuhe M','Packung',860),
('Regale','Handschuhe L','Packung',870),
('Regale','Mehrwegbowl','Stück',880),
-- Lager
('Lager','Große Togo Tüte','Kartons (250 Stk)',890),
('Lager','Kleine Togo Tüte','Kartons (250 Stk)',900),
('Lager','Schwarze Serviette','Karton',910),
('Lager','Nachos','Karton (12 Beutel)',920),
('Lager','Spüli','Flasche',930),
('Lager','Essigessenz','Flasche',940),
('Lager','Topfschwamm','Packung (10Stk)',950),
('Lager','Edelstahlschwamm','Packung (10Stk)',960),
('Lager','Reinigungshandschuhe','Packung (2Stk)',970),
('Lager','Blaue Rolle','Rolle',980),
('Lager','Toilettenpapier','Packung',990),
('Lager','Glasreiniger','Kanister',1000),
('Lager','WC Reiniger','Kanister',1010),
('Lager','Desinfektionsreiniger','Kanister',1020),
('Lager','Gastro Universal Reiniger','Kanister',1030),
('Lager','Kalkreiniger','Kanister',1040),
('Lager','Laminat - Parkett-Reiniger','Kanister',1050),
('Lager','B100N','Kanister',1060),
('Lager','B200S','Kanister',1070),
('Lager','F8500','Kanister',1080),
('Lager','F420E','Kanister',1090),
('Lager','Spülmaschine Salz - Etolit','Beutel',1100);
